In [1]:
import numpy as np

### **1. Trasformare cicli in list comprehension**

Fai tre esempi di cicli producono una lista e poi riscrivi lo stesso codice usando la list comprehension

In [10]:
quadrati = []
for x in range(10):
    quadrati.append(x**2)
print(quadrati)
Num = [20, 70, 45, 90]
Num_over50 = []
for n in Num:
    if n > 50:
        Num_over50.append(n)
print(Num_over50)
numeri = [1, 2, 3, 4, 5]
risultato_ciclo = []

for x in numeri:
    risultato_ciclo.append(x * 10)

print(risultato_ciclo)

[0, 1, 4, 9, 16, 25, 36, 49, 64, 81]
[70, 90]
[10, 20, 30, 40, 50]


In [11]:
Quadrati = [x**2 for x in range(10)]
print(Quadrati)
Num_over50 = [n for n in Num if n > 50]
print(Num_over50)
numeri_np = np.array([1, 2, 3, 4, 5])
risultato_np = numeri_np * 10
print(risultato_np)

[0, 1, 4, 9, 16, 25, 36, 49, 64, 81]
[70, 90]
[10 20 30 40 50]


### **2. Vettore di Numeri Primi**

1. **Crea un vettore** contenente tutti i numeri primi compresi tra **0 e 10**  
   _(Puoi scriverli direttamente nell'array)._

2. **Conta quanti numeri ci sono nel vettore** utilizzando la funzione `len()`.  **Ottieni lo stesso numero** accedendo all'attributo `.size` del vettore.

3. Quale pensi sia il tipo di dato (`dtype`) del vettore?  Prova a rispondere senza eseguire il codice e Verifica la tua risposta accedendo all'attributo `.dtype` del vettore

4. Scrivi l'array usando una list comprehension che controlla che i numeri siano primi. 

In [2]:

def is_primo(x):
    w=0
    for i in range(2,x-1): 
        
        if x%(i)==0:
            w=1
    if w==0:
        return True
    else:
        return False
a=np.array([x for x in range(10) if is_primo(x)])
print(a)

[0 1 2 3 5 7]


In [ ]:
print(len(a))
print(a.size)
print(a.dtype)



6
6
int64


### **3.  Operazioni su array**
Crea un array **a**, 1D (senza digitarlo esplicitamente), e genera due nuovi array **b**, contenente una sottostringa a piacere e **c** che è il reverse dell'array **a** (esempio [1,2,3] diventa [3,2,1]) .  Dividi l'array **a** per l'array **c**. Fai la stessa cosa per una lista.

In [25]:
A=np.random.randint(1,100,10)
b=A[3:7]
c=A[::-1]
print(A,c)
A/c

[51 37 63 42  5 30 47 57 37 30] [30 37 57 47 30  5 42 63 37 51]


array([1.7       , 1.        , 1.10526316, 0.89361702, 0.16666667,
       6.        , 1.11904762, 0.9047619 , 1.        , 0.58823529])